/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RedirectToUserPostRouteImport } from './routes/redirectToUserPost'
import { Route as RedirectToUserRouteImport } from './routes/redirectToUser'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserIdIndexRouteImport } from './routes/user/$id/index'
import { Route as UserIdPostPostIdRouteImport } from './routes/user/$id/post/$postId'

const RedirectToUserPostRoute = RedirectToUserPostRouteImport.update({
  id: '/redirectToUserPost',
  path: '/redirectToUserPost',
  getParentRoute: () => rootRouteImport,
} as any)
const RedirectToUserRoute = RedirectToUserRouteImport.update({
  id: '/redirectToUser',
  path: '/redirectToUser',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserIdIndexRoute = UserIdIndexRouteImport.update({
  id: '/user/$id/',
  path: '/user/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserIdPostPostIdRoute = UserIdPostPostIdRouteImport.update({
  id: '/user/$id/post/$postId',
  path: '/user/$id/post/$postId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/redirectToUser': typeof RedirectToUserRoute
  '/redirectToUserPost': typeof RedirectToUserPostRoute
  '/user/$id': typeof UserIdIndexRoute
  '/user/$id/post/$postId': typeof UserIdPostPostIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/redirectToUser': typeof RedirectToUserRoute
  '/redirectToUserPost': typeof RedirectToUserPostRoute
  '/user/$id': typeof UserIdIndexRoute
  '/user/$id/post/$postId': typeof UserIdPostPostIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/redirectToUser': typeof RedirectToUserRoute
  '/redirectToUserPost': typeof RedirectToUserPostRoute
  '/user/$id/': typeof UserIdIndexRoute
  '/user/$id/post/$postId': typeof UserIdPostPostIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/redirectToUser'
    | '/redirectToUserPost'
    | '/user/$id'
    | '/user/$id/post/$postId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/redirectToUser'
    | '/redirectToUserPost'
    | '/user/$id'
    | '/user/$id/post/$postId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/redirectToUser'
    | '/redirectToUserPost'
    | '/user/$id/'
    | '/user/$id/post/$postId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  RedirectToUserRoute: typeof RedirectToUserRoute
  RedirectToUserPostRoute: typeof RedirectToUserPostRoute
  UserIdIndexRoute: typeof UserIdIndexRoute
  UserIdPostPostIdRoute: typeof UserIdPostPostIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/redirectToUserPost': {
      id: '/redirectToUserPost'
      path: '/redirectToUserPost'
      fullPath: '/redirectToUserPost'
      preLoaderRoute: typeof RedirectToUserPostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redirectToUser': {
      id: '/redirectToUser'
      path: '/redirectToUser'
      fullPath: '/redirectToUser'
      preLoaderRoute: typeof RedirectToUserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/$id/': {
      id: '/user/$id/'
      path: '/user/$id'
      fullPath: '/user/$id'
      preLoaderRoute: typeof UserIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/$id/post/$postId': {
      id: '/user/$id/post/$postId'
      path: '/user/$id/post/$postId'
      fullPath: '/user/$id/post/$postId'
      preLoaderRoute: typeof UserIdPostPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  RedirectToUserRoute: RedirectToUserRoute,
  RedirectToUserPostRoute: RedirectToUserPostRoute,
  UserIdIndexRoute: UserIdIndexRoute,
  UserIdPostPostIdRoute: UserIdPostPostIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
