import fs from "node:fs";
import path from "node:path";

const resourcesDir = path.join(__dirname, "../src/resources/en");
const keysDir = path.join(__dirname, "../src/keys");

if (!fs.existsSync(keysDir)) {
  fs.mkdirSync(keysDir, { recursive: true });
}

function generateKeysForNamespace(ns: string) {
  const jsonPath = path.join(resourcesDir, `${ns}.json`);
  const content = JSON.parse(fs.readFileSync(jsonPath, "utf-8"));

  const keys = Object.keys(content);

  const className = `${ns.charAt(0).toUpperCase()}${ns.slice(1)}Keys`;

  const fileContent = `/**
 * AUTO-GENERATED FILE. DO NOT MODIFY.
 * This file was generated by scripts/generate-keys.ts
 */
import { TKey } from "../types";

export const ${className} = {
${keys.map((key) => `  ${key}: "${key}" as const as TKey<"${ns}">,`).join("\n")}
} as const;
`;

  fs.writeFileSync(path.join(keysDir, `${ns}.ts`), fileContent);
  console.log(`Generated keys for namespace: ${ns}`);
}

const namespaces = fs
  .readdirSync(resourcesDir)
  .filter((file) => file.endsWith(".json"))
  .map((file) => file.replace(".json", ""));

namespaces.forEach(generateKeysForNamespace);

// Also generate a types.ts if it doesn't exist or update TKey
const typesPath = path.join(__dirname, "../src/types.ts");
const typesContent = `export type TKey<Namespace extends string> = string & { __brand: Namespace };
`;
fs.writeFileSync(typesPath, typesContent);
