/**
 * AUTO-GENERATED FILE. DO NOT MODIFY.
 * This file was generated by scripts/generate-keys.ts
 */
import type { TKey } from "../types";

export const CommonKeys = {
  genericError: "genericError" as const as TKey<"common">,
  retry: "retry" as const as TKey<"common">,
  goBackHome: "goBackHome" as const as TKey<"common">,
  notFoundTitle: "notFoundTitle" as const as TKey<"common">,
  notFoundMessage: "notFoundMessage" as const as TKey<"common">,
} as const;
