/**
 * AUTO-GENERATED FILE. DO NOT MODIFY.
 * This file was generated by scripts/generate-keys.ts
 */
import type { TKey } from "../types";

export const HomeKeys = {
  welcome: "welcome" as const as TKey<"home">,
  description: "description" as const as TKey<"home">,
  toggleLanguage: "toggleLanguage" as const as TKey<"home">,
  detectedLanguage: "detectedLanguage" as const as TKey<"home">,
} as const;
